name: getx_dio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^0.6.0
  get: ^4.3.7
  dio: ">=3.0.10 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
